# Generated by Django 5.0.2 on 2024-08-27 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carro_circuito_corrida_equipe_piloto_sponsor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField()),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corrida')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.piloto')),
            ],
        ),
    ]
